version: '3.9'

services:

  postgres_db:
    container_name: postgres_db
    image: postgres:15-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3

  redis_db:
    container_name: redis_db
    image: redis:latest
    command: --port ${REDIS_PORT}
    volumes:
      - redis-data:/data
    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 15s
      retries: 5

  tasks:
    container_name: tasks
    build: ./
    ports:
      - ${TASKS_PORT}:${TASKS_PORT}
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: true
      redis_db:
        condition: service_healthy
    env_file: 
      - .env

volumes:
  pg-data:
  redis-data: